import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from './context/AuthProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type LayoutProps = {
  children: React.ReactNode;
};

/**
 * Application layout
 * @param {Readonly<LayoutProps>} props
 * @return {JSX.Element} The rendered component
 */
export default function RootLayout({ children }: Readonly<LayoutProps>): JSX.Element {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <main className='flex grainy-light flex-col min-h-[calc(100vh-10rem-1px)]'>
            <div className='flex-1 flex flex-col h-full'>{children}</div>
          </main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
